#!/bin/sh
#
# jq with json highlighting
jq() {
    # check if we get data from pipe and didn't set options
    if [[ -z "$@" ]] && [[ -p /dev/stdin ]]; then
        set -- '.' "${@:2}"
    fi

    # use raw output for redirect
    if [[ -t 1 ]] ; then
        /usr/local/bin/jq "$@" | source-highlight -f esc -s json --style-file json.style --data-dir=/usr/local/share/source-highlight 
    else
        /usr/local/bin/jq "$@"
    fi
}

