#!/bin/sh
#
# jq with json highlighting
jq() { 
    # check if we get data from pipe and didn't set options
    if [[ -z "$@" ]] && [[ -p /dev/stdin ]]; then
        set -- '.' "${@:2}"
    fi
    /usr/local/bin/jq "$@" | source-highlight -f esc -s json --style-file json.style 
}

