frame = "full"
title-hidden = false
system-native-tabs = false
system-pinned-hotkey = false
system-switcher-hotkey = false
system-quit-hotkey = "cmd+w"
vsync = true
idle = true
fork = true

[font]
normal = ["SF Mono"]
size = 14.0

[[font.italic]]
family = "JetBrains Mono"
style = "Italic"

[[font.bold_italic]]
family = "JetBrains Mono"
style = "Bold Italic"
