icon = "/Users/nnguyen2/.config/neovide/icon.icns"
frame = "full"
title-hidden = false
system-native-tabs = false
system-pinned-hotkey = ""
system-switcher-hotkey = ""
system-quit-hotkey = ""
vsync = true
idle = true
fork = true

[font]
normal = ["SF Mono"]
size = 14.0

[[font.italic]]
family = "JetBrains Mono"
style = "Italic"

[[font.bold_italic]]
family = "JetBrains Mono"
style = "Bold Italic"
